# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'iPadControls' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  pod "PlainPing"
  pod 'ReaderFramework', '~> 1.1.4'
  pod 'Alamofire'
  pod 'NMSSH'
  pod 'Charts' 
  # Pods for iPadControls

end
